# Generated by Django 6.0.8 on 2026-08-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('win_rate', models.FloatField(blank=True, help_text='0.0-1.0', null=True)),
                ('profit_factor', models.FloatField(blank=True, null=True)),
                ('expectancy', models.FloatField(blank=True, help_text='Average R per trade', null=True)),
                ('avg_r', models.FloatField(blank=True, null=True)),
                ('max_drawdown', models.FloatField(blank=True, help_text='As a % of equity', null=True)),
                ('slippage', models.FloatField(blank=True, help_text='Average slippage, in price units', null=True)),
                ('false_signal_rate', models.FloatField(blank=True, help_text='0.0-1.0', null=True)),
            ],
            options={
                'db_table': 'performance_metrics',
                'ordering': ['-date'],
            },
        ),
    ]
