# Generated by Django 6.0.8 on 2026-08-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemetrics',
            name='net_pnl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net realized P&L for the day, in rupees (gross profit minus gross loss across all closed OpenPosition rows that day). Null when total_trades is 0.', max_digits=14, null=True),
        ),
    ]
