# Generated by Django 6.0.8 on 2026-08-08 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('signal_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('no_trade', 'No Trade')], max_length=16)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('stop_loss', models.DecimalField(decimal_places=4, max_digits=14)),
                ('target_1', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('target_2', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('position_size', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('total_score', models.FloatField()),
                ('technical_score', models.FloatField()),
                ('sentiment_score', models.FloatField()),
                ('risk_score', models.FloatField()),
                ('options_score', models.FloatField(default=0.5, help_text='Options-chain confirmation score from apps.options.signals_engine.options_confluence_score() -- 0.5 (neutral) when no options data is synced for the symbol yet.')),
                ('regime', models.CharField(choices=[('trending', 'Trending'), ('sideways', 'Sideways'), ('high_volatility', 'High Volatility / Event-Driven')], max_length=32)),
                ('ml_win_probability', models.FloatField(blank=True, help_text="Win-probability from apps.learning.ml_train's logistic-regression model (see that module's docstring), scored at signal-creation time via apps.learning.ml_predict. Purely advisory -- for the dashboard and daily review to read alongside the four rule-based scores above. NULL until a model has been trained (needs apps.learning.ml_train.MIN_TRAINING_SAMPLES closed trades) and never gates BUY/NO_TRADE on its own; the rule engine above this field is still the only thing that decides approved/rejected.", null=True)),
                ('ind_rsi', models.FloatField(blank=True, help_text='RSI (0-100) at signal time.', null=True)),
                ('ind_adx', models.FloatField(blank=True, help_text='ADX (0-100) at signal time.', null=True)),
                ('ind_bb_width', models.FloatField(blank=True, help_text='Bollinger band width as a fraction of the middle band (already unitless).', null=True)),
                ('ind_relative_volume', models.FloatField(blank=True, help_text='Volume vs. its 20-period average, as a ratio.', null=True)),
                ('ind_atr_pct', models.FloatField(blank=True, help_text='ATR divided by close price (scale-free volatility).', null=True)),
                ('ind_macd_hist_pct', models.FloatField(blank=True, help_text='MACD histogram divided by close price.', null=True)),
                ('ind_ema9_slope_pct', models.FloatField(blank=True, help_text='EMA9 candle-over-candle change divided by close price.', null=True)),
                ('ind_ema21_slope_pct', models.FloatField(blank=True, help_text='EMA21 candle-over-candle change divided by close price.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executed', 'Executed'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('reason', models.TextField(help_text='Human-readable explanation, especially for rejections -- this is what the daily review reads.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('strategy_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='learning.strategyversion')),
            ],
            options={
                'db_table': 'trading_signals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', '-created_at'], name='trading_sig_symbol_5dcba2_idx'), models.Index(fields=['status'], name='trading_sig_status_a509a8_idx')],
            },
        ),
    ]
