# Generated by Django 6.0.8 on 2026-08-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsignal',
            name='option_side',
            field=models.CharField(blank=True, choices=[('CE', 'Call'), ('PE', 'Put')], help_text="CE or PE -- which option side this signal's suggested contract is on (apps.options.strike_selector.suggest_best_strike), distinct from signal_type (BUY/SELL), which reflects how the underlying position that actually executes is opened.", max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='strike_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The suggested option contract's strike, when option_side is set.", max_digits=12, null=True),
        ),
    ]
