# Generated by Django 6.0.8 on 2026-08-17 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_optioncontract_lot_size_optioncontract_tradingsymbol'),
        ('signals', '0002_tradingsignal_option_side_tradingsignal_strike_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsignal',
            name='option_contract',
            field=models.ForeignKey(blank=True, help_text="Set only by apps.options.index_direction_strategy when suggest_best_strike resolved an actual OptionContract row for this signal -- this (not option_side/strike_price, which are display-only) is what apps.execution.paper_executor keys off to open a real option-premium position instead of the underlying-index proxy. entry_price/stop_loss/target_1/target_2 are in OPTION PREMIUM terms whenever this is set, not index points -- see index_direction_strategy's own docstring.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='options.optioncontract'),
        ),
    ]
