# Generated by Django 6.0.8 on 2026-08-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_tradingsignal_option_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsignal',
            name='rejection_stage',
            field=models.CharField(blank=True, choices=[('direction', 'Underlying Direction'), ('success_rate', 'Historical Success Rate'), ('sentiment', 'Sentiment Veto'), ('options_confluence', 'Options-Chain Confluence'), ('expiry', 'Expiry Selection'), ('strike', 'Strike Selection'), ('liquidity', 'Liquidity Validation'), ('risk', 'Risk Validation'), ('ml_confidence', 'ML Confidence'), ('lot_size', 'Lot-Size Rounding')], help_text="Only set by apps.options.index_direction_strategy, on a REJECTED/NO_TRADE signal, to the first pipeline stage that added a reason to `reasons` -- lets the frontend render a real 'which stage did this die at' lifecycle waterfall instead of parsing the free-text `reason` string. Null for APPROVED signals and for every signal apps.signals.engine.generate_signal produces (that engine has no equivalent multi-stage pipeline to attribute a rejection to).", max_length=24, null=True),
        ),
    ]
