# Generated by Django 6.0.8 on 2026-08-18 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_alter_tradingsignal_rejection_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalFeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.JSONField(help_text="apps.options.feature_store.build_feature_vector's output -- see that function's own docstring for the exact field set.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_snapshot', to='signals.tradingsignal')),
            ],
            options={
                'db_table': 'signal_feature_snapshots',
            },
        ),
    ]
