# Generated by Django 6.0.8 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signals", "0006_signalfeaturesnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradingsignal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("executing", "Executing"),
                    ("rejected", "Rejected"),
                    ("executed", "Executed"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="tradingsignal",
            name="execution_mode",
            field=models.CharField(
                choices=[("paper", "Paper"), ("live", "Live")],
                db_index=True,
                default="paper",
                help_text="Execution venue intended when this signal was generated.",
                max_length=8,
            ),
        ),
    ]
