# Generated by Django 6.0.8 on 2026-08-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('timeframe', models.CharField(help_text='e.g. 1m, 5m, 10m, 15m, 30m, 1h, 1d (see broker_client.TIMEFRAME_TO_ANGEL_INTERVAL)', max_length=8)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=14)),
                ('high', models.DecimalField(decimal_places=4, max_digits=14)),
                ('low', models.DecimalField(decimal_places=4, max_digits=14)),
                ('close', models.DecimalField(decimal_places=4, max_digits=14)),
                ('volume', models.BigIntegerField(default=0)),
                ('source', models.CharField(help_text='e.g. angel_one, nse_historical', max_length=64)),
            ],
            options={
                'db_table': 'historical_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', '-timestamp'], name='historical__symbol_bdae2a_idx')],
                'unique_together': {('symbol', 'timeframe', 'timestamp')},
            },
        ),
    ]
