# Generated by Django 6.0.8 on 2026-08-08 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, help_text="Human-readable actor for system-triggered actions with no Django user attached, e.g. 'risk_engine' or 'celery:run_daily_review'.", max_length=150)),
                ('action', models.CharField(db_index=True, help_text='e.g. kill_switch_rearmed, strategy_version_promoted, daily_review_approved, order_placed, order_rejected', max_length=100)),
                ('target_type', models.CharField(blank=True, help_text='e.g. StrategyVersion, OpenPosition', max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='audit_log_action_7c9e02_idx')],
            },
        ),
    ]
