# Generated by Django 6.0.8 on 2026-08-08 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(help_text='e.g. angel_one_ws, nse_historical', max_length=64)),
                ('is_healthy', models.BooleanField()),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'feed_health_checks',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['source', '-checked_at'], name='feed_health_source_cdbd9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('condition', models.CharField(choices=[('above', 'Crosses above'), ('below', 'Crosses below')], max_length=8)),
                ('target_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('active', models.BooleanField(default=True, help_text='False once triggered (or manually cancelled).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'price_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'active'], name='price_alert_symbol_c31853_idx')],
            },
        ),
    ]
