# Generated by Django 6.0.8 on 2026-08-08 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOutlookSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bias', models.CharField(help_text='Bullish / Bearish / Neutral', max_length=16)),
                ('bias_confidence', models.FloatField(blank=True, help_text='0.0-1.0, when derivable.', null=True)),
                ('summary', models.TextField(help_text='The full explained narrative -- what JARVIS actually says.')),
                ('best_options_idea', models.CharField(blank=True, max_length=255)),
                ('best_stock_idea', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'market_outlook_snapshots',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='JarvisMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_json', models.JSONField(default=dict, help_text='Small, overwritten-in-place: current_page, active_strategy, last_command, last_intent, preferences. Not a transcript.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jarvis_memory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jarvis_memory',
            },
        ),
        migrations.CreateModel(
            name='JarvisCommandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(help_text='The command exactly as received (voice-transcribed or typed).')),
                ('input_mode', models.CharField(default='text', help_text='voice | text | chat -- manual 14.6 Input Modes.', max_length=16)),
                ('intent_category', models.CharField(blank=True, max_length=32)),
                ('intent_action', models.CharField(blank=True, max_length=64)),
                ('executed_module', models.CharField(blank=True, help_text="Which apps.jarvis handler (or downstream app) actually ran, e.g. 'risk.get_equity'.", max_length=64)),
                ('result_text', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('needs_confirmation', models.BooleanField(default=False, help_text='True when this command was a restricted action (manual 14.21) and JARVIS asked for confirmation instead of executing it.')),
                ('execution_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jarvis_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jarvis_command_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='jarvis_comm_created_092872_idx'), models.Index(fields=['intent_category'], name='jarvis_comm_intent__a812c7_idx')],
            },
        ),
    ]
