# Generated by Django 6.0.8 on 2026-08-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('side', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=8)),
                ('qty', models.PositiveIntegerField()),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('stop_loss', models.DecimalField(decimal_places=4, max_digits=14)),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('trailing_stop_distance', models.DecimalField(blank=True, decimal_places=4, help_text='If set, apps.execution.trailing_stop ratchets stop_loss up as peak_price makes new highs, trailing by this distance. Set at open time from (entry_price - stop_loss) when settings.TRAILING_STOP_ENABLED -- null means trailing is off for this position (the pre-trailing-stop default).', max_digits=14, null=True)),
                ('peak_price', models.DecimalField(blank=True, decimal_places=4, help_text='Highest price seen since entry -- only tracked when trailing_stop_distance is set.', max_digits=14, null=True)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'open_positions',
                'ordering': ['-opened_at'],
            },
        ),
    ]
