# Generated by Django 6.0.8 on 2026-08-08 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0001_initial'),
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openposition',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='signals.tradingsignal'),
        ),
        migrations.AddIndex(
            model_name='openposition',
            index=models.Index(fields=['symbol'], name='open_positi_symbol_2a1d45_idx'),
        ),
        migrations.AddIndex(
            model_name='openposition',
            index=models.Index(fields=['closed_at'], name='open_positi_closed__a0c99c_idx'),
        ),
    ]
