# Generated by Django 6.0.8 on 2026-08-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionModeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('paper', 'Paper'), ('live', 'Live')], default='paper', max_length=8)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.CharField(blank=True, help_text='Who last changed this -- switching to LIVE enables real order placement with real money, so this is always attributed to a specific logged-in user, same posture as KillSwitchState.deactivated_by.', max_length=150)),
            ],
            options={
                'db_table': 'execution_mode_setting',
            },
        ),
    ]
