# Generated by Django 6.0.8 on 2026-08-17 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_executionmodesetting'),
        ('options', '0002_optioncontract_lot_size_optioncontract_tradingsymbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='openposition',
            name='option_contract',
            field=models.ForeignKey(blank=True, help_text="Set only when this position is a real option-premium position (copied from signal.option_contract at open time, see paper_executor.open_position_from_signal) -- entry_price/stop_loss/target_price are OPTION PREMIUM, not index points, whenever this is set, and check_and_close_positions fetches this contract's own live LTP (apps.options.pricing.latest_ltp_for_contract) instead of compute_indicators(symbol), which has no candle history for an option contract's own symbol.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='options.optioncontract'),
        ),
    ]
