# Generated by Django 6.0.8 on 2026-08-19

import uuid

import django.db.models.deletion
from django.db import migrations, models


def ensure_no_legacy_open_positions(apps, schema_editor):
    """Do not silently classify an existing live position as paper."""
    OpenPosition = apps.get_model("execution", "OpenPosition")
    if OpenPosition.objects.filter(closed_at__isnull=True).exists():
        raise RuntimeError(
            "Open positions exist. Close/reconcile and classify them before applying "
            "the execution-venue migration."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0004_openposition_option_contract"),
        ("signals", "0007_alter_tradingsignal_status"),
    ]

    operations = [
        migrations.RunPython(ensure_no_legacy_open_positions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="openposition",
            name="signal",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="positions",
                to="signals.tradingsignal",
            ),
        ),
        migrations.AddField(
            model_name="openposition",
            name="execution_mode",
            field=models.CharField(
                choices=[("paper", "Paper"), ("live", "Live")],
                db_index=True,
                default="paper",
                help_text=(
                    "Execution venue that opened this position; paper and live "
                    "positions must never share an exit path."
                ),
                max_length=8,
            ),
        ),
        migrations.AddIndex(
            model_name="openposition",
            index=models.Index(
                fields=["execution_mode", "closed_at"],
                name="open_pos_mode_closed_idx",
            ),
        ),
        migrations.AddField(
            model_name="openposition",
            name="timeframe",
            field=models.CharField(
                db_index=True,
                default="5m",
                help_text="Candle timeframe that owns this position's exit decisions.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="openposition",
            name="strategy_key",
            field=models.CharField(
                blank=True,
                help_text="Optional strategy owner used to keep concurrent execution loops isolated.",
                max_length=64,
            ),
        ),
        migrations.AddIndex(
            model_name="openposition",
            index=models.Index(
                fields=["execution_mode", "timeframe", "closed_at"],
                name="open_pos_mode_tf_closed_idx",
            ),
        ),
        migrations.CreateModel(
            name="BrokerOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idempotency_key", models.UUIDField(default=uuid.uuid4, editable=False, help_text="Sent as Angel One's ordertag and used for reconciliation.", unique=True)),
                ("purpose", models.CharField(choices=[("open", "Open"), ("close", "Close"), ("flatten", "Emergency flatten")], max_length=12)),
                ("symbol", models.CharField(db_index=True, max_length=64)),
                ("side", models.CharField(choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4)),
                ("quantity", models.PositiveIntegerField()),
                ("status", models.CharField(choices=[("created", "Created locally"), ("submitted", "Submitted"), ("filled", "Filled"), ("cancelled", "Cancelled"), ("rejected", "Rejected"), ("unknown", "Broker state unknown")], db_index=True, default="created", max_length=12)),
                ("broker_order_id", models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ("filled_quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("average_fill_price", models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="broker_orders", to="execution.openposition")),
                ("signal", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="broker_orders", to="signals.tradingsignal")),
            ],
            options={
                "db_table": "broker_orders",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "-created_at"], name="broker_ord_status_62f37e_idx"),
                    models.Index(fields=["signal", "purpose"], name="broker_ord_signal_16d16f_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("signal", "purpose"), name="uniq_broker_signal_purpose"),
                ],
            },
        ),
    ]
