# Generated by Django 6.0.8 on 2026-08-08 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEquity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_equity', models.DecimalField(decimal_places=2, max_digits=16)),
                ('daily_start_equity', models.DecimalField(decimal_places=2, max_digits=16)),
                ('peak_equity', models.DecimalField(decimal_places=2, max_digits=16)),
                ('consecutive_losses', models.PositiveSmallIntegerField(default=0)),
                ('trading_day', models.DateField(help_text='Which trading day daily_start_equity refers to')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'account_equity',
            },
        ),
        migrations.CreateModel(
            name='EquitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
            options={
                'db_table': 'equity_snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='equity_snap_timesta_1b6ac4_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=32)),
                ('event_type', models.CharField(help_text='e.g. drawdown_breach, stale_feed, broker_mismatch, daily_loss_limit, exposure_limit, kill_switch_triggered', max_length=64)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'risk_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', '-created_at'], name='risk_events_severit_a66025_idx')],
            },
        ),
        migrations.CreateModel(
            name='KillSwitchState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_by', models.CharField(blank=True, help_text="Manual re-arming must always be a deliberate human action per the manual's safety rules -- record who did it.", max_length=150)),
                ('triggered_by_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk.riskevent')),
            ],
            options={
                'db_table': 'kill_switch_state',
            },
        ),
    ]
