# Generated by Django 6.0.8 on 2026-08-08 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(unique=True)),
                ('summary', models.TextField()),
                ('suggested_changes', models.JSONField(default=dict)),
                ('approved_flag', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'daily_review_notes',
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='DriftEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('drift_type', models.CharField(help_text='e.g. data_drift, prediction_drift', max_length=64)),
                ('metric_name', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=16)),
                ('action_taken', models.CharField(blank=True, help_text='e.g. rollback, quarantine, none', max_length=64)),
            ],
            options={
                'db_table': 'drift_events',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=100, unique=True)),
                ('params_json', models.JSONField(default=dict)),
                ('active_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'strategy_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('artifact_path', models.CharField(max_length=500)),
                ('metrics_json', models.JSONField(default=dict)),
                ('active_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'model_registry',
                'ordering': ['-created_at'],
                'unique_together': {('model_name', 'model_version')},
            },
        ),
        migrations.CreateModel(
            name='TradeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_multiple', models.FloatField(blank=True, help_text='P&L divided by planned risk (qty x |entry - stop|). Null if risk was zero/unknown.', null=True)),
                ('reward_score', models.IntegerField(blank=True, help_text='manual 11.10/13.9 discrete reward band -- see apps.learning.reward.compute_reward_score.', null=True)),
                ('confidence_band', models.CharField(default='Unrated', help_text="manual 13.10 label for the signal's ml_win_probability at entry time.", max_length=32)),
                ('mistake_tags', models.JSONField(default=list, help_text='manual 11.13/13.14 categories this trade matched -- see apps.learning.mistakes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='execution.openposition')),
            ],
            options={
                'db_table': 'trade_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
