# Generated by Django 6.0.8 on 2026-08-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HypotheticalTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('trend_following', 'Trend Following'), ('mean_reversion', 'Mean Reversion'), ('breakout', 'Breakout')], db_index=True, max_length=32)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('timeframe', models.CharField(default='5m', max_length=8)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('stop_loss', models.DecimalField(decimal_places=4, max_digits=14)),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('exit_reason', models.CharField(blank=True, choices=[('stop', 'Stop Loss'), ('target', 'Target'), ('timeout', 'Max Holding Period')], max_length=16)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('r_multiple', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hypothetical_trades',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['method', '-opened_at'], name='hypothetica_method_366d3e_idx')],
            },
        ),
    ]
