# Generated by Django 6.0.8 on 2026-08-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_hypotheticaltrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypotheticaltrade',
            name='method',
            field=models.CharField(choices=[('trend_following', 'Trend Following'), ('mean_reversion', 'Mean Reversion'), ('breakout', 'Breakout'), ('ema_momentum_scalp', 'EMA Momentum Scalp'), ('rsi_extreme_scalp', 'RSI Extreme Reversal Scalp'), ('sar_volume_burst_scalp', 'SAR + Volume Burst Scalp')], db_index=True, max_length=32),
        ),
    ]
