# Generated by Django 6.0.8 on 2026-08-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_hypotheticaltrade_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypotheticaltrade',
            name='option_side',
            field=models.CharField(blank=True, choices=[('CE', 'Call'), ('PE', 'Put')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hypotheticaltrade',
            name='strike_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
