# Generated by Django 6.0.8 on 2026-08-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_hypotheticaltrade_option_side_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypotheticaltrade',
            name='ind_adx',
            field=models.FloatField(blank=True, help_text='ADX (0-100) at open time.', null=True),
        ),
        migrations.AddField(
            model_name='hypotheticaltrade',
            name='ind_atr_pct',
            field=models.FloatField(blank=True, help_text='ATR divided by close price (scale-free volatility).', null=True),
        ),
        migrations.AddField(
            model_name='hypotheticaltrade',
            name='ind_bb_width',
            field=models.FloatField(blank=True, help_text='Bollinger band width as a fraction of the middle band (already unitless).', null=True),
        ),
        migrations.AddField(
            model_name='hypotheticaltrade',
            name='ind_ema21_slope_pct',
            field=models.FloatField(blank=True, help_text='EMA21 candle-over-candle change divided by close price.', null=True),
        ),
        migrations.AddField(
            model_name='hypotheticaltrade',
            name='ind_ema9_slope_pct',
            field=models.FloatField(blank=True, help_text='EMA9 candle-over-candle change divided by close price.', null=True),
        ),
        migrations.AddField(
            model_name='hypotheticaltrade',
            name='ind_macd_hist_pct',
            field=models.FloatField(blank=True, help_text='MACD histogram divided by close price.', null=True),
        ),
        migrations.AddField(
            model_name='hypotheticaltrade',
            name='ind_relative_volume',
            field=models.FloatField(blank=True, help_text='Volume vs. its 20-period average, as a ratio.', null=True),
        ),
        migrations.AddField(
            model_name='hypotheticaltrade',
            name='ind_rsi',
            field=models.FloatField(blank=True, help_text='RSI (0-100) at open time.', null=True),
        ),
        migrations.AddField(
            model_name='hypotheticaltrade',
            name='ml_win_probability',
            field=models.FloatField(blank=True, help_text="Win-probability from apps.learning.scalp_ml_train's own logistic-regression model (trained ONLY on closed scalping HypotheticalTrade rows -- a separate model from apps.signals.models.TradingSignal.ml_win_probability's, see apps.learning.scalp_ml_train's module docstring for why they're kept apart), scored at open time via apps.learning.scalp_ml_predict. Purely advisory, same as the real model's field -- never gates which ideas open, so the daily method-comparison ranking keeps measuring each method's own unfiltered performance. NULL until a model has been trained (needs apps.learning.scalp_ml_train.MIN_TRAINING_SAMPLES closed scalps).", null=True),
        ),
    ]
