# Generated by Django 6.0.8 on 2026-08-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_hypotheticaltrade_ind_adx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_environment', models.CharField(choices=[('PAPER', 'Paper'), ('LIVE', 'Live')], db_index=True, default='PAPER', max_length=8)),
                ('model_name', models.CharField(db_index=True, help_text="Matches the ModelRegistry.model_name this sample was collected for, e.g. 'paper_trading_policy'.", max_length=100)),
                ('decision_ref', models.CharField(blank=True, help_text="The source decision's UUID (e.g. PaperAIDecision.decision_id) as a string -- no cross-app FK, same reasoning as apps.admin_tools.audit's target_type/target_id pattern.", max_length=64)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='The decision moment this sample was captured at -- training splits are always ordered by this field, never by created_at.')),
                ('feature_schema_version', models.CharField(max_length=16)),
                ('feature_vector_json', models.JSONField(default=dict)),
                ('label', models.IntegerField(help_text='1 = win / correct-to-trade, 0 = loss / correct-to-skip -- the binary classification target.')),
                ('net_r', models.FloatField(blank=True, help_text='net_pnl_after_charges / initial_risk -- stored alongside the binary label for regression-style or R-weighted training.', null=True)),
                ('is_hypothetical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'training_samples',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['model_name', 'source_environment', 'timestamp'], name='training_sample_lookup_idx')],
            },
        ),
    ]
