# Generated by Django 6.0.8 on 2026-08-08 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=32)),
                ('headline', models.TextField()),
                ('source', models.CharField(max_length=128)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('sentiment_label', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=16)),
                ('sentiment_score', models.FloatField(help_text='Normalized -1.0 (very negative) to +1.0 (very positive)')),
                ('confidence', models.FloatField(help_text='Model confidence 0.0-1.0')),
                ('news_category', models.CharField(blank=True, help_text='e.g. earnings, macro, regulatory, company-specific', max_length=64)),
            ],
            options={
                'db_table': 'news_sentiment',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['symbol', '-published_at'], name='news_sentim_symbol_397959_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsImpactAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectors', models.JSONField(default=list, help_text='Sector names this headline was matched to.')),
                ('likely_rising_stocks', models.JSONField(default=list, help_text='Tickers, if sentiment was positive and directly mentioned.')),
                ('likely_falling_stocks', models.JSONField(default=list, help_text='Tickers, if sentiment was negative and directly mentioned.')),
                ('index_impact', models.CharField(blank=True, help_text='Rough directional read on NIFTY/BANKNIFTY if this headline is macro/sector-wide, else blank.', max_length=16)),
                ('confidence', models.FloatField(help_text='Same FinBERT confidence carried over -- see impact_engine for why.')),
                ('time_horizon', models.CharField(help_text='intraday / multi_day / unspecified', max_length=16)),
                ('trade_relevance', models.CharField(choices=[('direct', 'Direct (named stock mentioned)'), ('sector', 'Sector-wide'), ('macro', 'Macro / index-wide'), ('none', 'No clear market relevance')], max_length=16)),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact_analysis', to='news.newssentiment')),
            ],
            options={
                'db_table': 'news_impact_analysis',
            },
        ),
    ]
