# Generated by Django 6.0.8 on 2026-08-08 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underlying', models.CharField(db_index=True, help_text='e.g. NIFTY, BANKNIFTY', max_length=32)),
                ('expiry', models.DateField(db_index=True)),
                ('strike', models.DecimalField(decimal_places=2, max_digits=12)),
                ('option_type', models.CharField(choices=[('CE', 'Call'), ('PE', 'Put')], max_length=2)),
                ('symbol_token', models.CharField(help_text="Broker's symboltoken for this specific contract -- needed to fetch quotes for it.", max_length=32, unique=True)),
            ],
            options={
                'db_table': 'option_contracts',
                'ordering': ['underlying', 'expiry', 'strike'],
                'indexes': [models.Index(fields=['underlying', 'expiry'], name='option_cont_underly_1dc0e3_idx')],
                'unique_together': {('underlying', 'expiry', 'strike', 'option_type')},
            },
        ),
        migrations.CreateModel(
            name='OptionChainSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('ltp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('open_interest', models.BigIntegerField()),
                ('change_in_oi', models.BigIntegerField(help_text='OI change vs. the previous snapshot for this contract -- computed at ingestion time, not derived on every read.')),
                ('volume', models.BigIntegerField(default=0)),
                ('iv', models.FloatField(blank=True, help_text='Implied volatility, as a percentage', null=True)),
                ('bid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ask', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='options.optioncontract')),
            ],
            options={
                'db_table': 'option_chain_snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['contract', '-timestamp'], name='option_chai_contrac_d5be9c_idx')],
                'unique_together': {('contract', 'timestamp')},
            },
        ),
    ]
