# Generated by Django 6.0.8 on 2026-08-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optioncontract',
            name='lot_size',
            field=models.PositiveIntegerField(default=0, help_text="Contract's minimum tradeable quantity -- real orders must be a whole multiple of this."),
        ),
        migrations.AddField(
            model_name='optioncontract',
            name='tradingsymbol',
            field=models.CharField(default='', help_text="Broker's tradingsymbol for this contract (e.g. 'NIFTY28AUG25024500CE') -- required (alongside symbol_token) to actually place an order on this exact contract, as opposed to just fetching its quote.", max_length=64),
        ),
    ]
