# Generated by Django 6.0.8 on 2026-08-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_optioncontract_lot_size_optioncontract_tradingsymbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsStrategySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_mode', models.CharField(choices=[('current_week', 'Current Week'), ('next_week', 'Next Week'), ('monthly', 'Monthly'), ('custom', 'Custom Expiry')], default='current_week', max_length=16)),
                ('strike_mode', models.CharField(choices=[('atm', 'ATM'), ('itm', 'ITM'), ('otm', 'OTM'), ('ai', 'AI Selected')], default='ai', max_length=8)),
                ('itm_otm_steps', models.PositiveSmallIntegerField(default=1, help_text='How many strikes ITM/OTM to step from ATM when strike_mode is ITM or OTM.')),
                ('custom_expiry', models.DateField(blank=True, help_text='Only used when expiry_mode=CUSTOM -- must match an actually-synced OptionContract expiry.', null=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'options_strategy_setting',
            },
        ),
    ]
