# Generated by Django 6.0.8 on 2026-08-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_optionsstrategysetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_weight', models.FloatField(default=0.18)),
                ('momentum_weight', models.FloatField(default=0.12)),
                ('oi_weight', models.FloatField(default=0.15)),
                ('volume_weight', models.FloatField(default=0.07)),
                ('skew_weight', models.FloatField(default=0.08)),
                ('greeks_weight', models.FloatField(default=0.1)),
                ('liquidity_weight', models.FloatField(default=0.13)),
                ('expected_move_weight', models.FloatField(default=0.08)),
                ('risk_reward_weight', models.FloatField(default=0.09)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'options_scoring_weights',
            },
        ),
    ]
