# Generated by Django 6.0.8 on 2026-08-18 14:58

from django.db import migrations, models
from django.utils import timezone


def _deactivate_already_expired_contracts(apps, schema_editor):
    """
    One-time backfill for rows that predate the is_active field: any
    contract whose expiry is strictly before today (unambiguous
    regardless of settings.OPTIONS_EXPIRY_CUTOFF_TIME, since a past
    calendar date is never eligible under any cutoff) is marked
    inactive immediately on migrate, rather than waiting for the next
    scheduled sync/rollover task to get around to it. Contracts
    expiring TODAY are deliberately left at the field's own default
    (True) here -- whether "today" is still eligible depends on the
    real cutoff time, which is apps.options.expiry_service's job, not a
    migration's; the daily sync/rollover Celery tasks (config/celery.py)
    keep is_active correct for that case going forward.
    """
    OptionContract = apps.get_model("options", "OptionContract")
    OptionContract.objects.filter(expiry__lt=timezone.localdate()).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_scoringweights'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underlying', models.CharField(db_index=True, max_length=32, unique=True)),
                ('last_successful_sync', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_result', models.JSONField(blank=True, help_text='Most recent sync_underlying_contracts() summary: expiries synced, inserted/updated/deactivated/skipped counts -- same shape the management command prints and the health check reads.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'option_sync_status',
            },
        ),
        migrations.AddField(
            model_name='optioncontract',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this contract is currently eligible to be traded/quoted -- maintained by apps.options.contract_sync using apps.options.expiry_service.is_expiry_eligible (cutoff-aware: a contract expiring TODAY stays active until settings.OPTIONS_EXPIRY_CUTOFF_TIME, not just until midnight). Never a reason to delete a row -- historical/expired contracts stay in the table (is_active=False) so past OptionChainSnapshot data remains attached for backtesting/analytics; live-trading code should filter on this instead of re-deriving expiry eligibility itself.'),
        ),
        migrations.AddIndex(
            model_name='optioncontract',
            index=models.Index(fields=['underlying', 'is_active'], name='option_cont_underly_e9a58e_idx'),
        ),
        migrations.RunPython(_deactivate_already_expired_contracts, migrations.RunPython.noop),
    ]
