# Generated by Django 6.0.8 on 2026-08-19 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0005_optionsyncstatus_optioncontract_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(help_text='e.g. 1m, 5m, 15m -- same convention as HistoricalData.timeframe', max_length=8)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=14)),
                ('high', models.DecimalField(decimal_places=4, max_digits=14)),
                ('low', models.DecimalField(decimal_places=4, max_digits=14)),
                ('close', models.DecimalField(decimal_places=4, max_digits=14)),
                ('volume', models.BigIntegerField(default=0)),
                ('source', models.CharField(default='angel_one', help_text='e.g. angel_one (REST backfill), angel_one_live (tick aggregation)', max_length=64)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='options.optioncontract')),
            ],
            options={
                'db_table': 'option_candles',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['contract', 'timeframe', '-timestamp'], name='option_cand_contrac_b38b6a_idx')],
                'unique_together': {('contract', 'timeframe', 'timestamp')},
            },
        ),
    ]
