# Generated by Django 6.0.8 on 2026-08-08 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "NIFTY 50", "NIFTY BANK", "SENSEX"', max_length=64, unique=True)),
                ('symbol', models.CharField(help_text='Broker-style display ticker, e.g. NIFTY, BANKNIFTY, SENSEX.', max_length=32)),
                ('exchange', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE')], default='NSE', max_length=8)),
            ],
            options={
                'db_table': 'indices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IPOListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('symbol', models.CharField(blank=True, help_text='Assigned once listed.', max_length=32)),
                ('exchange', models.CharField(blank=True, help_text='e.g. NSE, BSE, NSE+BSE', max_length=16)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('price_band_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_band_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('issue_size_crores', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('open', 'Open for subscription'), ('closed', 'Closed, awaiting listing'), ('listed', 'Listed')], default='upcoming', max_length=16)),
                ('subscription_times', models.FloatField(blank=True, help_text='Overall subscription multiple, once available.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ipo_listings',
                'ordering': ['-open_date'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=128)),
                ('exchange', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE')], default='NSE', max_length=8)),
                ('listed_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stocks',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='FundamentalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_end', models.DateField(help_text='Last date of the reported quarter/year.')),
                ('reporting_type', models.CharField(choices=[('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=16)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, help_text='In INR crores.', max_digits=18, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, help_text='In INR crores.', max_digits=18, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('revenue_growth_yoy', models.FloatField(blank=True, help_text='% vs same period last year.', null=True)),
                ('profit_growth_yoy', models.FloatField(blank=True, help_text='% vs same period last year.', null=True)),
                ('roe', models.FloatField(blank=True, help_text='Return on equity, %.', null=True)),
                ('roce', models.FloatField(blank=True, help_text='Return on capital employed, %.', null=True)),
                ('debt_to_equity', models.FloatField(blank=True, null=True)),
                ('promoter_holding_pct', models.FloatField(blank=True, null=True)),
                ('pe_ratio', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(help_text='e.g. nse_corporate_results', max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundamentals', to='investing.stock')),
            ],
            options={
                'db_table': 'fundamental_snapshots',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='StockPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='investing.stock')),
            ],
            options={
                'db_table': 'stock_price_history',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StockRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundamental_score', models.FloatField(help_text="0-100 composite heuristic score -- fundamentals, valuation, AND technical trend combined (see apps.investing.fundamental_score.WEIGHTS). Named for backward compatibility with the field's original fundamentals-only version.")),
                ('verdict', models.CharField(choices=[('strong_hold', 'Strong long-term hold candidate'), ('moderate_hold', 'Moderate hold candidate'), ('watch', 'Watch, not yet a hold candidate'), ('avoid', "Fundamentals don't support a hold right now")], max_length=16)),
                ('suggested_hold_months', models.PositiveIntegerField(blank=True, help_text='None when verdict is WATCH/AVOID -- there is no hold suggestion to make.', null=True)),
                ('valuation_label', models.CharField(blank=True, help_text='Low/Medium/High -- see apps.investing.valuation. Blank if PE data was unavailable.', max_length=16)),
                ('technical_trend', models.CharField(blank=True, help_text='See apps.investing.technical_score. Blank if insufficient price history was available.', max_length=24)),
                ('reasoning', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('based_on', models.ForeignKey(blank=True, help_text='The latest snapshot this score was computed from.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='investing.fundamentalsnapshot')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='investing.stock')),
            ],
            options={
                'db_table': 'stock_recommendations',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='StockWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='investing.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_watchlist',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='IndexPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('ltp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('change_pct', models.FloatField(blank=True, null=True)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='investing.index')),
            ],
            options={
                'db_table': 'index_price_snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['index', '-timestamp'], name='index_price_index_i_cd9ace_idx')],
            },
        ),
        migrations.CreateModel(
            name='IndexConstituent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_pct', models.FloatField(blank=True, help_text="Index weight, when NSE's response includes it.", null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('change_pct', models.FloatField(blank=True, help_text='% change from previous close, from the last sync.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituents', to='investing.index')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_memberships', to='investing.stock')),
            ],
            options={
                'db_table': 'index_constituents',
                'ordering': ['-weight_pct'],
                'unique_together': {('index', 'stock')},
            },
        ),
        migrations.AddIndex(
            model_name='fundamentalsnapshot',
            index=models.Index(fields=['stock', '-period_end'], name='fundamental_stock_i_945de5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fundamentalsnapshot',
            unique_together={('stock', 'period_end', 'reporting_type')},
        ),
        migrations.AddIndex(
            model_name='stockpricehistory',
            index=models.Index(fields=['stock', '-date'], name='stock_price_stock_i_b0972d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockpricehistory',
            unique_together={('stock', 'date')},
        ),
        migrations.AddIndex(
            model_name='stockrecommendation',
            index=models.Index(fields=['stock', '-generated_at'], name='stock_recom_stock_i_3e5ec0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockwatchlist',
            unique_together={('user', 'stock')},
        ),
    ]
